# -*- coding: utf-8 -*-
"""Stream provenance and disjointness audit (zero token).

Provenance: source split, selection rule, sha256 of the derived files.
Disjointness: every stream and calibration item against all 1,100 evaluation
items at three levels: exact text; normalized text (lowercase, whitespace
collapsed, punctuation removed, numbers kept); 5-gram token Jaccard. difflib
SequenceMatcher runs only with --with-difflib.

Inputs
    --datasets  datasets (in git: benchmark/, train_set/)
    --out       default reanalysis/reviewer_round

Input availability key: "in git" = shipped in this repository; "release
asset" = the v1.0.0 GitHub release asset admitor-v1.0.0-runlogs.zip; "private,
not distributed" = kept by the authors (<host> below is the OptSkills host
clone the experiments ran in).

Reproduce (from the repository root)
    python scripts/disjointness_audit.py

Outputs
    <out>/06_provenance.md, 06_similarity_pairs.md, 06_max_similarity.csv

Paper location
    Section 4 setup and Appendix C "Stream provenance and disjointness".
"""
from __future__ import annotations

import argparse
import collections
import csv
import hashlib
import json
import os
import re
import sys

PLATES = ["complexor", "industryor", "mamo_complex_test",
          "optmath_bench", "optibench"]
PUNCT = re.compile(r"[^\w\s]")
WS = re.compile(r"\s+")


def norm(t):
    return WS.sub(" ", PUNCT.sub(" ", (t or "").lower())).strip()


def grams(t, n=5):
    w = norm(t).split()
    return {tuple(w[i:i + n]) for i in range(max(0, len(w) - n + 1))}


def sha(p):
    h = hashlib.sha256()
    with open(p, "rb") as f:
        for c in iter(lambda: f.read(1 << 20), b""):
            h.update(c)
    return h.hexdigest()


def load(p, key="question"):
    out = []
    for line in open(p, encoding="utf-8"):
        if line.strip():
            r = json.loads(line)
            out.append((str(r.get("index", r.get("idx", len(out)))), r.get(key, "")))
    return out


def main():
    ap = argparse.ArgumentParser(description="Task 6 provenance and disjointness.")
    ap.add_argument("--datasets", default="datasets")
    ap.add_argument("--out", default="reanalysis/reviewer_round")
    ap.add_argument("--with-difflib", action="store_true")
    a = ap.parse_args()
    D = a.datasets

    stream = load(os.path.join(D, "train_set", "optmath-train-300-blind.jsonl"))
    calib = load(os.path.join(D, "train_set", "nano-co.jsonl"))
    evals = []
    for name in PLATES:
        p = os.path.join(D, "benchmark", name + ".jsonl")
        if os.path.isfile(p):
            for i, q in load(p):
                evals.append((name, i, q))

    L = ["# Task 6. Stream provenance and disjointness", "",
         "Zero-token. Generated by `admitor-infra/disjointness_audit.py`.", "",
         "## 6.1 Provenance", "", "| File | records | sha256 |", "|---|---:|---|"]
    for rel in [("train_set", "optmath-train-300.jsonl"),
                ("train_set", "optmath-train-300-blind.jsonl"),
                ("train_set", "nano-co.jsonl"),
                ("vault", "optmath-train-300-labels.jsonl")]:
        p = os.path.join(D, *rel)
        if os.path.isfile(p):
            n = sum(1 for l in open(p, encoding="utf-8") if l.strip())
            L.append("| `%s` | %d | `%s` |" % ("/".join(rel), n, sha(p)))
    src = load(os.path.join(D, "train_set", "optmath-train-300.jsonl"))
    idx = [int(i) for i, _ in src if str(i).isdigit()]
    contiguous = sorted(idx) == list(range(min(idx), max(idx) + 1))
    L += ["",
          "Stream source: the OptMATH training split shipped with the host as "
          "`datasets/train_set/optmath-train-300.jsonl`. Index range %d to %d, "
          "contiguous: %s, so the selection rule is the first 300 by index "
          "rather than a seeded sample. The blind file is that file with the "
          "answer column removed and the vault is its idx/answer projection; "
          "both regenerate byte-identically via `scripts/regen_derived.py`."
          % (min(idx), max(idx), "yes" if contiguous else "no"),
          "",
          "Calibration: NANO-CO, %d instances available. `e3_calibrate.py "
          "cmd_workorder` stratifies by `problem_type` with seed 42: each type "
          "list is shuffled once, then types are visited in sorted order "
          "round-robin until 150 are collected." % len(calib),
          ""]

    ev_exact = collections.defaultdict(list)
    ev_norm = collections.defaultdict(list)
    for plate, i, q in evals:
        ev_exact[q].append((plate, i))
        ev_norm[norm(q)].append((plate, i))
    ev_grams = [(plate, i, grams(q), q) for plate, i, q in evals]

    rows, pairs = [], []
    for label, items in (("stream", stream), ("calibration", calib)):
        for i, q in items:
            e = len(ev_exact.get(q, []))
            nmt = len(ev_norm.get(norm(q), []))
            g = grams(q)
            best, bestp = 0.0, None
            for plate, j, gg, qq in ev_grams:
                if not g or not gg:
                    continue
                inter = len(g & gg)
                if not inter:
                    continue
                jac = inter / len(g | gg)
                if jac > best:
                    best, bestp = jac, (plate, j, qq)
            rows.append(dict(set=label, item=i, exact_matches=e,
                             normalized_matches=nmt, max_jaccard=round(best, 4),
                             nearest_plate=bestp[0] if bestp else "",
                             nearest_item=bestp[1] if bestp else ""))
            if e or nmt or best >= 0.8:
                pairs.append((label, i, q, e, nmt, best, bestp))

    L += ["## 6.2 Disjointness against the evaluation items", "",
          "Evaluation items loaded: %d." % len(evals), "",
          "| Set | items | exact | normalized | Jaccard >= 0.8 | max Jaccard |",
          "|---|---:|---:|---:|---:|---:|"]
    for label in ("stream", "calibration"):
        rs = [r for r in rows if r["set"] == label]
        L.append("| %s | %d | %d | %d | %d | %.4f |"
                 % (label, len(rs), sum(r["exact_matches"] for r in rs),
                    sum(r["normalized_matches"] for r in rs),
                    sum(1 for r in rs if r["max_jaccard"] >= 0.8),
                    max((r["max_jaccard"] for r in rs), default=0.0)))
    L += ["", "Ten highest maximum Jaccard values:", "",
          "| Set | item | max Jaccard | nearest plate | nearest item |",
          "|---|---|---:|---|---|"]
    for r in sorted(rows, key=lambda x: -x["max_jaccard"])[:10]:
        L.append("| %s | %s | %.4f | %s | %s |"
                 % (r["set"], r["item"], r["max_jaccard"],
                    r["nearest_plate"], r["nearest_item"]))
    L += ["", "difflib SequenceMatcher: %s."
          % ("run" if a.with_difflib else
             "not run (scope cut of 2026-09-17; 5-gram Jaccard reported)"), ""]

    open(os.path.join(a.out, "06_provenance.md"), "w",
         encoding="utf-8", newline="\n").write("\n".join(L) + "\n")
    with open(os.path.join(a.out, "06_max_similarity.csv"), "w",
              encoding="utf-8", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)

    P = ["# Task 6. Pairs above either threshold", ""]
    if not pairs:
        P += ["No stream or calibration item matched any evaluation item "
              "exactly, after normalization, or at 5-gram Jaccard >= 0.8.", ""]
    for label, i, q, e, nmt, best, bp in pairs:
        P += ["## %s item %s (exact %d, normalized %d, Jaccard %.4f)"
              % (label, i, e, nmt, best), "", "```", q[:1200], "```", "",
              "nearest: %s" % (str(bp[:2]) if bp else "-"), "",
              "```", (bp[2][:1200] if bp else ""), "```", ""]
    open(os.path.join(a.out, "06_similarity_pairs.md"), "w",
         encoding="utf-8", newline="\n").write("\n".join(P) + "\n")

    print("wrote 06_provenance.md, 06_similarity_pairs.md, 06_max_similarity.csv")
    for label in ("stream", "calibration"):
        rs = [r for r in rows if r["set"] == label]
        print("  %-12s n=%d exact=%d norm=%d jac>=0.8=%d max=%.4f"
              % (label, len(rs), sum(r["exact_matches"] for r in rs),
                 sum(r["normalized_matches"] for r in rs),
                 sum(1 for r in rs if r["max_jaccard"] >= 0.8),
                 max((r["max_jaccard"] for r in rs), default=0.0)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
