"""Format the paired-bootstrap stdout into release/reviewer_round/04_bootstrap.md.

Purpose
    corrected_bootstrap.py prints its intervals to stdout, captured as
    04_bootstrap_raw.txt. The markdown report 04_bootstrap.md was originally
    assembled by hand in an earlier session from that stdout, and its command
    block was garbled when written (backslash sequences such as `\\v` and `\\r`
    in Windows paths became control characters). This script rebuilds the report
    from the raw stdout so that every number in it is parsed, not typed, and
    writes the command block with forward slashes. The prose is kept as in the
    original report; the summary sentences are checked against the parsed
    intervals and the script stops if they no longer hold.

Inputs
    --raw   release/reviewer_round/04_bootstrap_raw.txt (in git)
    --out   default release/reviewer_round/04_bootstrap.md

Reproduce (from the repository root)
    python scripts/format_bootstrap_report.py

Outputs
    <out>, the markdown report.

Paper location
    Section 4.2 intervals and Appendix C.
"""
import argparse
import re
import sys

PAIR = re.compile(r"^\s+(gate - \w+)\s+macro ([+-]\d+\.\d+)\s+95% \[([+-]\d+\.\d+), ([+-]\d+\.\d+)\]\s+P\(>0\)=(\d\.\d+)")
MICRO = re.compile(r"^\s+micro ([+-]\d+\.\d+)\s+95% \[([+-]\d+\.\d+), ([+-]\d+\.\d+)\]\s+P\(>0\)=(\d\.\d+)")
ARM = re.compile(r"^\s+(gt|vote|runsok|gate)\s+macro\s+(\d+\.\d+)\s+micro\s+(\d+\.\d+)")

COMMAND = """```powershell
conda activate optskills
python scripts/corrected_bootstrap.py run `
    --arm gt=<run-records>/outputs/e1/eval/gt `
    --arm vote=<run-records>/outputs/e1/eval/vote `
    --arm runsok=<run-records>/outputs/e1/eval/runsok `
    --arm gate=<run-records>/outputs/e1/eval/gate `
    --rule-arm gt --rule-plate optibench --reps 10000 --seed 42 `
    --score-eval scripts/score_eval.py --out release/reviewer_round
```"""


def parse(raw):
    blocks, cur = {}, None
    for line in raw.splitlines():
        if line.startswith("====="):
            if "UNCORRECTED" in line:
                cur = "R0"
            elif "R1 flagged" in line:
                cur = "R1"
            else:
                cur = None
            if cur:
                blocks[cur] = {"pairs": [], "arms": {}}
            last = None
            continue
        if cur is None:
            continue
        m = ARM.match(line)
        if m:
            blocks[cur]["arms"][m.group(1)] = (m.group(2), m.group(3))
            continue
        m = PAIR.match(line)
        if m:
            last = dict(pair=m.group(1), macro=m.groups()[1:])
            blocks[cur]["pairs"].append(last)
            continue
        m = MICRO.match(line)
        if m and last is not None:
            last["micro"] = m.groups()
    return blocks


def excludes_zero(lo, hi):
    return float(lo) > 0 or float(hi) < 0


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--raw", default="release/reviewer_round/04_bootstrap_raw.txt")
    ap.add_argument("--out", default="release/reviewer_round/04_bootstrap.md")
    a = ap.parse_args()
    b = parse(open(a.raw, encoding="utf-8").read())
    if set(b) != {"R0", "R1"} or any(len(b[k]["pairs"]) != 3 for k in b):
        sys.exit("could not parse the R0 and R1 blocks with three pairs each")
    rows, ex = [], {}
    for pair in ("gate - gt", "gate - vote", "gate - runsok"):
        for scale in ("macro", "micro"):
            for basis in ("R0", "R1"):
                rec = next(p for p in b[basis]["pairs"] if p["pair"] == pair)
                d, lo, hi, p = rec[scale]
                e = excludes_zero(lo, hi)
                ex[(pair, scale, basis)] = e
                rows.append("| `%s` | %s | %s | %s | [%s, %s] | %s | %s |"
                            % (pair, scale, basis, d, lo, hi, p, "yes" if e else "**no**"))
    expected = {
        ("gate - gt", "macro", "R0"): True, ("gate - gt", "macro", "R1"): True,
        ("gate - gt", "micro", "R0"): True, ("gate - gt", "micro", "R1"): False,
        ("gate - vote", "macro", "R0"): True, ("gate - vote", "macro", "R1"): True,
        ("gate - vote", "micro", "R0"): False, ("gate - vote", "micro", "R1"): False,
        ("gate - runsok", "macro", "R0"): False, ("gate - runsok", "macro", "R1"): False,
        ("gate - runsok", "micro", "R0"): False, ("gate - runsok", "micro", "R1"): False,
    }
    if ex != expected:
        sys.exit("the summary sentences no longer match the parsed intervals; update them")
    arms = b["R0"]["arms"]
    r0 = {p["pair"]: p for p in b["R0"]["pairs"]}
    L = [
        "# Task 4. Paired bootstrap, all three pairs, both scales, both bases",
        "",
        "Zero-token. Generated by `admitor-infra/corrected_bootstrap.py` (unmodified; the pairs it",
        "already emits for `--target gate` cover all three comparisons).",
        "",
        COMMAND,
        "",
        "Seed 42, 10,000 paired resamples stratified by plate. R0 = all 1,100 items;",
        "R1 = the 85 `e1_eval_failure` rows of the ground-truth arm on OptiBench removed",
        "from all four arms.",
        "",
        "Reconciliation gates, all passed: the R0 macro column equals Table 2 exactly",
        "(gt %s, vote %s, runsok %s, gate %s); the two published intervals"
        % (arms["gt"][0], arms["vote"][0], arms["runsok"][0], arms["gate"][0]),
        "reproduce (gate-vote %s [%s, %s], gate-gt %s [%s, %s]);"
        % (tuple(r0["gate - vote"]["macro"][:3]) + tuple(r0["gate - gt"]["macro"][:3])),
        "the R1 block puts gt macro at %s." % b["R1"]["arms"]["gt"][0],
        "",
        "| Pair | Scale | Basis | Delta | 95% interval | P(>0) | Excludes zero |",
        "|---|---|---|---:|---|---:|---|",
    ] + rows + [
        "",
        "Summary: `gate - gt` excludes zero on macro at both bases and on micro at R0 only;",
        "`gate - vote` excludes zero on macro at both bases and on neither micro;",
        "`gate - runsok` **includes zero on both scales at both bases**.",
        "",
    ]
    open(a.out, "w", encoding="utf-8", newline="\n").write("\n".join(L) + "\n")
    print("wrote", a.out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
