# -*- coding: utf-8 -*-
"""Restricted K4 contingency (zero token).

The published K4 chi-square mixes solver crashes with value-level
disagreement. This restricts the table to candidates that reached value
comparison, and reports a 3x3 variant that adds infeasibility. The
permutation p-value is a fixed-margin Monte Carlo test (200,000 draws,
seed 42).

Inputs
    --matrix  artifacts/e3/k4_matrix.json (in git)
    --out     default reanalysis/reviewer_round

Input availability key: "in git" = shipped in this repository; "release
asset" = the v1.0.0 GitHub release asset admitor-v1.0.0-runlogs.zip; "private,
not distributed" = kept by the authors (<host> below is the OptSkills host
clone the experiments ran in).

Reproduce (from the repository root)
    python scripts/k4_restricted.py

Outputs
    <out>/08_k4_restricted.md

Paper location
    Section 4.2 (chi-square 8.75) and Appendix C.
"""
from __future__ import annotations
import argparse, itertools, json, math, os, sys

CLIQUE = "clique member"
EXCL = "solved, value excluded from clique"
INFEAS = "infeasible on instances"

try:
    from scipy.stats import chi2 as _chi2, fisher_exact
    HAVE = True
except ImportError:
    HAVE = False


def chisq(obs):
    rt = [sum(r) for r in obs]
    ct = [sum(obs[i][j] for i in range(len(obs))) for j in range(len(obs[0]))]
    n = sum(rt)
    s = 0.0
    for i in range(len(obs)):
        for j in range(len(obs[0])):
            e = rt[i] * ct[j] / n
            if e > 0:
                s += (obs[i][j] - e) ** 2 / e
    df = (len(obs) - 1) * (len(obs[0]) - 1)
    p = float(_chi2.sf(s, df)) if HAVE else float("nan")
    return s, df, p, n


def fisher_freeman_halton(obs, reps=200000, seed=42):
    """Fixed-margin Monte Carlo permutation test (r x c).

    Exact Freeman-Halton enumeration is intractable at these margins (the
    3x2 table alone has row totals in the hundreds), so the p-value is
    estimated by resampling tables with the observed margins and counting
    those at least as extreme under the chi-square statistic. With 200,000
    replicates the standard error on a p near 0.05 is about 0.0005.
    """
    import random
    rt = [sum(r) for r in obs]
    ct = [sum(obs[i][j] for i in range(len(obs))) for j in range(len(obs[0]))]
    n = sum(rt)
    obs_stat = chisq(obs)[0]
    # urn of column labels, shuffled and dealt into rows of fixed size
    urn = []
    for j, c in enumerate(ct):
        urn.extend([j] * c)
    rng = random.Random(seed)
    nr, nc = len(obs), len(obs[0])
    ge = 0
    for _ in range(reps):
        rng.shuffle(urn)
        t = [[0] * nc for _ in range(nr)]
        pos = 0
        for i in range(nr):
            for _k in range(rt[i]):
                t[i][urn[pos]] += 1
                pos += 1
        if chisq(t)[0] >= obs_stat - 1e-12:
            ge += 1
    return (ge + 1) / (reps + 1), None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--matrix", default="artifacts/e3/k4_matrix.json")
    ap.add_argument("--out", default="reanalysis/reviewer_round")
    a = ap.parse_args()
    m = json.load(open(a.matrix, encoding="utf-8"))["matrix"]
    arms = sorted(m)
    L = ["# Task 8. Restricted K4 contingency", "",
         "Zero-token. Generated by `admitor-infra/k4_restricted.py` from the same",
         "input as `k4_matrix.py`. scipy available: %s." % HAVE, ""]

    # full table for reference
    outs = sorted({o for c in m.values() for o in c})
    full = [[m[x].get(o, 0) for o in outs] for x in arms]
    s, df, p, n = chisq(full)
    L += ["## Published 3x5 table (reference)", "",
          "chi-square %.4f, df %d, p %.3g, n %d" % (s, df, p, n), ""]

    # 3x2 restricted
    L += ["## 3x2, restricted to candidates that reached value comparison", "",
          "| Arm | clique member | value excluded | row total |", "|---|---:|---:|---:|"]
    t2 = []
    for x in arms:
        r = [m[x].get(CLIQUE, 0), m[x].get(EXCL, 0)]
        t2.append(r)
        L.append("| `%s` | %d | %d | %d |" % (x, r[0], r[1], sum(r)))
    s2, df2, p2, n2 = chisq(t2)
    L += ["| **total** | **%d** | **%d** | **%d** |"
          % (sum(r[0] for r in t2), sum(r[1] for r in t2), n2), "",
          "chi-square **%.4f**, df **%d**, p **%.4g**, n %d" % (s2, df2, p2, n2), ""]
    ff, err = fisher_freeman_halton(t2)
    L += ["Fisher-Freeman-Halton exact: %s" % ("%.4g" % ff if ff is not None else err), ""]

    # 3x3 adding infeasible
    L += ["## 3x3, adding infeasible on instances", "",
          "| Arm | clique member | value excluded | infeasible | row total |",
          "|---|---:|---:|---:|---:|"]
    t3 = []
    for x in arms:
        r = [m[x].get(CLIQUE, 0), m[x].get(EXCL, 0), m[x].get(INFEAS, 0)]
        t3.append(r)
        L.append("| `%s` | %d | %d | %d | %d |" % (x, r[0], r[1], r[2], sum(r)))
    s3, df3, p3, n3 = chisq(t3)
    L += ["", "chi-square **%.4f**, df **%d**, p **%.4g**, n %d" % (s3, df3, p3, n3), ""]
    ff3, err3 = fisher_freeman_halton(t3)
    L += ["Fisher-Freeman-Halton exact: %s" % ("%.4g" % ff3 if ff3 is not None else err3), ""]

    open(os.path.join(a.out, "08_k4_restricted.md"), "w", encoding="utf-8",
         newline="\n").write("\n".join(L) + "\n")
    print("wrote 08_k4_restricted.md")
    print("published 3x5 : chi2=%.4f df=%d p=%.3g" % (s, df, p))
    print("restricted 3x2: chi2=%.4f df=%d p=%.4g  FFH=%s" % (s2, df2, p2, ff if ff is not None else err))
    print("3x3           : chi2=%.4f df=%d p=%.4g  FFH=%s" % (s3, df3, p3, ff3 if ff3 is not None else err3))
    return 0


if __name__ == "__main__":
    sys.exit(main())
