# -*- coding: utf-8 -*-
"""Retrieval concentration per arm and plate (zero token).

Reports, for every arm x plate: items, items with a recorded skill_id,
distinct library files retrieved, the most-retrieved file and the share of
items that retrieved it.

Inputs
    --eval-root  <host>/outputs/e1/eval (private, not distributed)
    --out        default reanalysis/reviewer_round

Input availability key: "in git" = shipped in this repository; "release
asset" = the v1.0.0 GitHub release asset admitor-v1.0.0-runlogs.zip; "private,
not distributed" = kept by the authors (<host> below is the OptSkills host
clone the experiments ran in).

Reproduce (from the repository root)
    python scripts/retrieval_stats.py --eval-root <host>/outputs/e1/eval

Outputs
    <out>/05b_retrieval_concentration.md

Paper location
    Section 4.2 (19 vs 30 files, 45%) and Appendix C Table 10.
"""
from __future__ import annotations
import argparse, collections, json, os, sys

ARMS = ["gt", "vote", "runsok", "gate"]
PLATES = ["complexor", "industryor", "mamo_c", "optmath", "optibench"]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--eval-root", required=True)
    ap.add_argument("--out", default="reanalysis/reviewer_round")
    a = ap.parse_args()
    os.makedirs(a.out, exist_ok=True)
    L = ["# Task 5(b). Retrieval concentration", "",
         "Zero-token. Generated by `admitor-infra/retrieval_stats.py`.",
         "Skill ids come from `skill_selection.skill_id` in the eval "
         "trajectories; the library file is `<skill_id>.md`.", "",
         "| Arm | Plate | items | with skill_id | distinct files | "
         "most-retrieved file | share |",
         "|---|---|---:|---:|---:|---|---:|"]
    for arm in ARMS:
        for plate in PLATES:
            p = os.path.join(a.eval_root, arm, plate, "trajectories.jsonl")
            if not os.path.isfile(p):
                continue
            ids, n = [], 0
            for line in open(p, encoding="utf-8"):
                if not line.strip():
                    continue
                n += 1
                ss = json.loads(line).get("skill_selection") or {}
                sk = ss.get("skill_id") if isinstance(ss, dict) else None
                if sk:
                    ids.append(str(sk))
            c = collections.Counter(ids)
            top, tn = (c.most_common(1)[0] if c else ("-", 0))
            L.append("| %s | %s | %d | %d | %d | `%s` | %.1f%% |"
                     % (arm, plate, n, len(ids), len(c), top,
                        100.0 * tn / n if n else 0.0))
    p = os.path.join(a.out, "05b_retrieval_concentration.md")
    open(p, "w", encoding="utf-8", newline="\n").write("\n".join(L) + "\n")
    print("wrote", p)
    return 0


if __name__ == "__main__":
    sys.exit(main())
