# -*- coding: utf-8 -*-
"""Retrieval and selection statistics (zero token).

(a) e1_eval_failure rows per arm and plate.
(b) distinct files retrieved, most-retrieved file and its share.
(c) round-aware accuracy conditional on selection success.

Selection success = the trajectory recorded a skill_id that names a file
present in that arm's library.

Inputs
    --eval-root  <host>/outputs/e1/eval (private, not distributed)
    --libs       artifacts/e1/libraries (in git)
    --out        default reanalysis/reviewer_round

Input availability key: "in git" = shipped in this repository; "release
asset" = the v1.0.0 GitHub release asset admitor-v1.0.0-runlogs.zip; "private,
not distributed" = kept by the authors (<host> below is the OptSkills host
clone the experiments ran in).

Reproduce (from the repository root)
    python scripts/retrieval_final.py --eval-root <host>/outputs/e1/eval

Outputs
    <out>/05_retrieval.md, 05_retrieval.csv

Paper location
    Section 4.2 (19 vs 30 files, 45%) and Appendix C Table 10.
"""
from __future__ import annotations
import argparse, collections, csv, json, os, sys
HERE = os.path.dirname(os.path.abspath(__file__)); sys.path.insert(0, HERE)
from score_eval import round_aware, to_num

ARMS = ["gt", "vote", "runsok", "gate"]
PLATES = ["complexor", "industryor", "mamo_c", "optmath", "optibench"]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--eval-root", required=True)
    ap.add_argument("--libs", default="artifacts/e1/libraries")
    ap.add_argument("--out", default="reanalysis/reviewer_round")
    a = ap.parse_args()
    os.makedirs(a.out, exist_ok=True)

    libs = {}
    for arm in ARMS:
        d = os.path.join(a.libs, "skill_library_%s" % arm)
        libs[arm] = {f[:-3] for f in os.listdir(d) if f.endswith(".md")} if os.path.isdir(d) else set()

    rows, L = [], []
    L += ["# Task 5. Retrieval and selection statistics", "",
          "Zero-token. Generated by `admitor-infra/retrieval_final.py`.",
          "Selection success = the row recorded a `skill_id` naming a file present in that arm's library.", "",
          "## (a) e1_eval_failure rows", "",
          "| Arm | " + " | ".join(PLATES) + " | total |", "|---|" + "---:|" * (len(PLATES) + 1)]
    fails = {}
    for arm in ARMS:
        r = []
        for plate in PLATES:
            p = os.path.join(a.eval_root, arm, plate, "trajectories.jsonl")
            n = sum(1 for l in open(p, encoding="utf-8")
                    if l.strip() and json.loads(l).get("e1_eval_failure")) if os.path.isfile(p) else 0
            r.append(n)
        fails[arm] = r
        L.append("| %s | %s | %d |" % (arm, " | ".join(str(x) for x in r), sum(r)))
    L += ["", "## (b) and (c) per arm and plate", "",
          "| Arm | Plate | items | with skill_id | in library | distinct files | "
          "most-retrieved | share | acc selection-success | acc selection-failure |",
          "|---|---|---:|---:|---:|---:|---|---:|---:|---:|"]
    for arm in ARMS:
        for plate in PLATES:
            p = os.path.join(a.eval_root, arm, plate, "trajectories.jsonl")
            if not os.path.isfile(p):
                continue
            ids, ok_s, ok_f, n = [], [], [], 0
            inlib = 0
            for line in open(p, encoding="utf-8"):
                if not line.strip():
                    continue
                r = json.loads(line); n += 1
                ss = r.get("skill_selection") or {}
                sk = ss.get("skill_id") if isinstance(ss, dict) else None
                ok = round_aware(to_num(r.get("prediction")), to_num(r.get("answer")), r.get("answer"))
                if sk:
                    ids.append(str(sk))
                    if str(sk) in libs[arm]:
                        inlib += 1; ok_s.append(ok)
                    else:
                        ok_f.append(ok)
                else:
                    ok_f.append(ok)
            c = collections.Counter(ids)
            top, tn = (c.most_common(1)[0] if c else ("-", 0))
            f = lambda v: "%.2f" % (100.0 * sum(v) / len(v)) if v else "-"
            L.append("| %s | %s | %d | %d | %d | %d | `%s` | %.1f%% | %s | %s |"
                     % (arm, plate, n, len(ids), inlib, len(c), top,
                        100.0 * tn / n if n else 0, f(ok_s), f(ok_f)))
            rows.append(dict(arm=arm, plate=plate, items=n, with_skill_id=len(ids),
                             in_library=inlib, distinct_files=len(c), top_file=top,
                             top_share=round(100.0 * tn / n, 2) if n else 0,
                             acc_selection_success=f(ok_s), acc_selection_failure=f(ok_f),
                             e1_eval_failure=fails[arm][PLATES.index(plate)]))
    L.append("")
    open(os.path.join(a.out, "05_retrieval.md"), "w", encoding="utf-8", newline="\n").write("\n".join(L) + "\n")
    with open(os.path.join(a.out, "05_retrieval.csv"), "w", encoding="utf-8", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=list(rows[0].keys())); w.writeheader(); w.writerows(rows)
    print("wrote 05_retrieval.md and .csv")
    for arm in ARMS:
        print("  %-7s e1_eval_failure per plate %s total %d" % (arm, fails[arm], sum(fails[arm])))
    return 0


if __name__ == "__main__":
    sys.exit(main())
