# -*- coding: utf-8 -*-
"""Reviewer-round inventory (zero token, read-only).

Purpose
    Verify every path, count and schema the reviewer-round analyses rely on,
    before any other analysis runs. Reports what is on disk; modifies nothing.

Inputs
    --root  the directory that holds the public checkout (AdmitOR/), the host
            clone (OptSkills-main/) and the private tool directory; default
            `..` when run from the repository root (private, not distributed:
            everything under the host clone and the tool directory)

Hard gates
    certify_runs verdict_full.json count == 298
    library file counts == gt 130 / vote 145 / runsok 163 / gate 101

Reproduce (from the repository root)
    python scripts/reviewer_inventory.py --root ..

Outputs
    <root>/AdmitOR/reanalysis/reviewer_round/00_inventory.md; a pass/fail
    summary on stdout, exit code 1 if a hard gate fails.

Paper location
    none (pre-analysis inventory; the gate counts are those of Table 2).
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import subprocess
import sys

OUT_REL = os.path.join("AdmitOR", "reanalysis", "reviewer_round")


def sh(cmd, cwd=None):
    try:
        p = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True, shell=False)
        return (p.stdout or p.stderr).strip()
    except Exception as e:
        return f"<{type(e).__name__}: {e}>"


def human(n):
    if n is None:
        return "-"
    for u in ("B", "KB", "MB", "GB"):
        if n < 1024 or u == "GB":
            return f"{n:.0f} {u}" if u == "B" else f"{n/1.0:.1f} {u}"
        n /= 1024.0
    return str(n)


def sz(p):
    try:
        return os.path.getsize(p)
    except OSError:
        return None


def count_lines(p):
    try:
        with open(p, encoding="utf-8", errors="replace") as f:
            return sum(1 for l in f if l.strip())
    except OSError:
        return None


def sha256(p, limit=None):
    try:
        h = hashlib.sha256()
        with open(p, "rb") as f:
            for chunk in iter(lambda: f.read(1 << 20), b""):
                h.update(chunk)
        return h.hexdigest()
    except OSError:
        return None


def main():
    ap = argparse.ArgumentParser(description="Reviewer-round Task 0 inventory.")
    ap.add_argument("--root", default="..")
    a = ap.parse_args()
    R = a.root
    out_dir = os.path.join(R, OUT_REL)
    os.makedirs(out_dir, exist_ok=True)
    L = []
    gates = []

    def w(s=""):
        L.append(s)

    w("# Task 0. Inventory")
    w()
    w("Zero-token, read-only. Generated by `admitor-infra/reviewer_inventory.py`.")
    w()
    w("Reproduce:")
    w()
    w("```powershell")
    w("conda activate admitor")
    w(f"python admitor-infra\\reviewer_inventory.py --root {R}")
    w("```")
    w()

    # ---------------- paths ----------------
    w("## 1. Expected paths")
    w()
    w("| Asserted path | Exists | Size | Count |")
    w("|---|---|---|---|")
    paths = [
        ("project root", R, "dir"),
        ("host clone", os.path.join(R, "OptSkills-main"), "dir"),
        ("public repo", os.path.join(R, "AdmitOR"), "dir"),
        ("private ops tree", os.path.join(R, "admitor-infra"), "dir"),
        ("stream certify_runs", os.path.join(R, "OptSkills-main", "outputs", "e1", "certify_runs"), "dir"),
        ("calibration outputs e3", os.path.join(R, "OptSkills-main", "outputs", "e3"), "dir"),
        ("e3_report_v06.json", os.path.join(R, "OptSkills-main", "outputs", "e3", "e3_report_v06.json"), "file"),
        ("nano-co.jsonl", os.path.join(R, "OptSkills-main", "datasets", "train_set", "nano-co.jsonl"), "jsonl"),
        ("vault labels", os.path.join(R, "admitor-infra", "vault", "optmath-train-300-labels.jsonl"), "jsonl"),
        ("blind stream", os.path.join(R, "OptSkills-main", "datasets", "train_set", "optmath-train-300-blind.jsonl"), "jsonl"),
        ("host runlog", os.path.join(R, "OptSkills-main", "runs", "host_llm.jsonl"), "jsonl"),
        ("e1 eval root", os.path.join(R, "OptSkills-main", "outputs", "e1", "eval"), "dir"),
        ("e1 libs root", os.path.join(R, "OptSkills-main", "outputs", "e1", "libs"), "dir"),
    ]
    info = {}
    for name, p, kind in paths:
        ex = os.path.exists(p)
        size = cnt = None
        if ex and kind == "file":
            size = sz(p)
        elif ex and kind == "jsonl":
            size, cnt = sz(p), count_lines(p)
        elif ex and kind == "dir":
            try:
                cnt = len(os.listdir(p))
            except OSError:
                cnt = None
        info[name] = (ex, p)
        w(f"| `{p}` | {'yes' if ex else '**NO**'} | {human(size)} | {cnt if cnt is not None else '-'} |")
    w()

    # ---------------- hard gate: certify_runs ----------------
    w("## 2. Hard gates")
    w()
    cr = os.path.join(R, "OptSkills-main", "outputs", "e1", "certify_runs")
    n_vf = 0
    if os.path.isdir(cr):
        n_vf = sum(1 for d in os.listdir(cr)
                   if os.path.isfile(os.path.join(cr, d, "verdict_full.json")))
    ok = n_vf == 298
    gates.append(("certify_runs verdict_full.json == 298", n_vf, ok))
    w(f"- stream `verdict_full.json` count: **{n_vf}** (expected 298) -> {'PASS' if ok else 'FAIL'}")

    libs = os.path.join(R, "OptSkills-main", "outputs", "e1", "libs")
    expect = {"gt": 130, "vote": 145, "runsok": 163, "gate": 101}
    for arm, want in expect.items():
        d = os.path.join(libs, f"skill_library_{arm}")
        got = len([f for f in os.listdir(d)]) if os.path.isdir(d) else None
        ok = got == want
        gates.append((f"library {arm} == {want}", got, ok))
        w(f"- library `{arm}`: **{got}** files (expected {want}) -> {'PASS' if ok else 'FAIL'}")
    w()

    # ---------------- schemas ----------------
    w("## 3. Observed schemas")
    w()

    def field_list(p):
        try:
            return sorted(json.load(open(p, encoding="utf-8")).keys())
        except Exception as e:
            return [f"<{type(e).__name__}: {e}>"]

    if os.path.isdir(cr):
        first = sorted(d for d in os.listdir(cr)
                       if os.path.isfile(os.path.join(cr, d, "verdict_full.json")))
        if first:
            p = os.path.join(cr, first[0], "verdict_full.json")
            w(f"**Stream `verdict_full.json`** (`{first[0]}`)")
            w()
            w("```")
            w(", ".join(field_list(p)))
            w("```")
            w()
    e3cr = os.path.join(R, "OptSkills-main", "outputs", "e3", "certify_runs")
    if os.path.isdir(e3cr):
        first = sorted(d for d in os.listdir(e3cr)
                       if os.path.isfile(os.path.join(e3cr, d, "verdict_full.json")))
        w(f"**Calibration `verdict_full.json`** ({len(first)} present, showing `{first[0] if first else '-'}`)")
        w()
        if first:
            w("```")
            w(", ".join(field_list(os.path.join(e3cr, first[0], "verdict_full.json"))))
            w("```")
            w()

    # eval rows, with and without the failure flag
    ev = os.path.join(R, "OptSkills-main", "outputs", "e1", "eval", "gt", "optibench", "trajectories.jsonl")
    if os.path.isfile(ev):
        flagged = unflagged = None
        for line in open(ev, encoding="utf-8"):
            if not line.strip():
                continue
            r = json.loads(line)
            if r.get("e1_eval_failure") and flagged is None:
                flagged = r
            elif not r.get("e1_eval_failure") and unflagged is None:
                unflagged = r
            if flagged and unflagged:
                break
        w("**Eval trajectory row keys**")
        w()
        w(f"- with `e1_eval_failure`: `{sorted(flagged.keys()) if flagged else 'none found'}`")
        w(f"- without: `{sorted(unflagged.keys()) if unflagged else 'none found'}`")
        w()

    # extracted specification location
    w("**Extracted specification (the `params` dict with `base`/`perturb`)**")
    w()
    spec_hits = []
    if os.path.isdir(cr):
        for d in sorted(os.listdir(cr))[:400]:
            sp = os.path.join(cr, d, "spec.json")
            if os.path.isfile(sp):
                spec_hits.append(sp)
    if spec_hits:
        try:
            s = json.load(open(spec_hits[0], encoding="utf-8"))
            w(f"- location: `<certify_runs>/<sample_id>/spec.json` ({len(spec_hits)} present)")
            w(f"- top-level keys: `{sorted(s.keys())}`")
            inner = s.get("spec") if isinstance(s.get("spec"), dict) else s
            k0 = sorted(inner.keys())[:3]
            w(f"- parameter names (first 3): `{k0}`")
            if k0:
                w(f"- one parameter: `{json.dumps(inner[k0[0]])[:220]}`")
        except Exception as e:
            w(f"- parse error: {type(e).__name__}: {e}")
    else:
        w("- **NOT FOUND** under `<certify_runs>/<sample_id>/spec.json`")
    w()

    # ---------------- scripts ----------------
    w("## 4. Scripts found in the tool directory")
    w()
    td = os.path.join(R, "admitor-infra")
    named = ["k4_matrix.py", "admitor_reanalysis.py", "e3_certificate_numbers.py",
             "review_packet.py", "disjointness_audit.py", "corrected_bootstrap.py",
             "CLAUDE_CODE_E5MINI.md"]
    w("| Work order asserts | Present |")
    w("|---|---|")
    for f in named:
        w(f"| `{f}` | {'yes' if os.path.isfile(os.path.join(td, f)) else '**NO**'} |")
    w()
    w("All files in `admitor-infra/`:")
    w()
    w("```")
    for f in sorted(os.listdir(td)) if os.path.isdir(td) else []:
        fp = os.path.join(td, f)
        if os.path.isfile(fp):
            w(f"{f}  ({human(sz(fp))})")
    w("```")
    w()

    # ---------------- git ----------------
    w("## 5. Public repo git state")
    w()
    repo = os.path.join(R, "AdmitOR")
    w("```")
    w("branch : " + sh(["git", "rev-parse", "--abbrev-ref", "HEAD"], repo))
    w("head   : " + sh(["git", "rev-parse", "--short", "HEAD"], repo))
    w("tags   : " + sh(["git", "tag"], repo).replace("\n", " "))
    w("remote : " + sh(["git", "remote", "get-url", "origin"], repo))
    st = sh(["git", "status", "--short"], repo)
    w("status : " + (st if st else "(clean)"))
    w("```")
    w()

    # ---------------- write ----------------
    path = os.path.join(out_dir, "00_inventory.md")
    open(path, "w", encoding="utf-8", newline="\n").write("\n".join(L) + "\n")
    print(f"wrote {path}")
    print()
    print("HARD GATES")
    bad = 0
    for name, got, ok in gates:
        print(f"  {'PASS' if ok else 'FAIL'}  {name}  (observed {got})")
        bad += 0 if ok else 1
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
